# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 20:01
from __future__ import unicode_literals

import acceptor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=acceptor.models.UploadedImage.generate_upload_path)),
            ],
        ),
    ]
